### PR TITLE
fix: allow empty list of NICs for Underlay setup if Multus is used

### LINKED ISSUE #150: Multus Network for ToR connectivity is not working
**Description**

I tried the alternative setup by using Multus to attach the 2nd interface supposed to give connectivity to the ToR as explained [here](https://openperouter.github.io/docs/configuration/#alternative-multus-network-for-top-of-rack-connectivity). However it seems that the feature is not fully implemented: the openperouter-router Pod is correctly built with 2 interfaces, but the configuration of a L2VNI for instance will make the openperouter-controller panic cause of "index out of range [0] with length 0".

Indeed, while the documentation mentions that we can omit the `nics` parameter in our Underlay configuration, it seems to be in fact mandatory when we look at the code here https://github.com/openperouter/openperouter/blob/29ab35fd558e06aff8bb04ce322971327d72ff32/internal/conversion/host_conversion.go#L31

There is probably a piece of code missing here to retrieve the interface dynamically created by Multus.

**Logs**
```
{"time":"2025-10-24T12:57:00.405970024Z","level":"INFO","msg":"start reconcile","controller":"RouterConfiguration","request":"openperouter-system/l2red"}
{"time":"2025-10-24T12:57:00.406161413Z","level":"INFO","msg":"frr generate config","event":"start"}
{"time":"2025-10-24T12:57:00.406515467Z","level":"INFO","msg":"updater writing frr file","file":"/etc/frr/frr.conf"}
{"time":"2025-10-24T12:57:00.406672061Z","level":"INFO","msg":"updater requesting update","url":"http://10.65.98.129:9080"}
{"time":"2025-10-24T12:57:00.679926676Z","level":"INFO","msg":"updater update requested"}
{"time":"2025-10-24T12:57:00.679940982Z","level":"INFO","msg":"frr generate config","event":"stop"}
{"time":"2025-10-24T12:57:00.682607032Z","level":"INFO","msg":"configure interface start","namespace":"cni-53afd385-c1bc-fea7-a6a5-da45e852d69c"}
{"time":"2025-10-24T12:57:00.682625657Z","level":"INFO","msg":"configure interface end","namespace":"cni-53afd385-c1bc-fea7-a6a5-da45e852d69c"}
{"time":"2025-10-24T12:57:00.682629574Z","level":"INFO","msg":"end reconcile","controller":"RouterConfiguration","request":"openperouter-system/l2red"}
{"time":"2025-10-24T12:57:00.682694486Z","level":"ERROR","msg":"Observed a panic","controller":"routercontroller","controllerGroup":"openpe.openperouter.github.io","controllerKind":"Underlay","Underlay":{"name":"l2red","namespace":"openperouter-system"},"namespace":"openperouter-system","name":"l2red","reconcileID":"bb933f1b-1a2a-433b-ae02-39ae56b71a93","panic":"runtime error: index out of range [0] with length 0","panicGoValue":"runtime.boundsError{x:0, y:0, signed:true, code:0x0}","stacktrace":"goroutine 243 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x211e7b8, 0xc000e78180}, {0x1cc3740, 0xc001a61d88})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.3/pkg/util/runtime/runtime.go:132 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:108 +0x112\npanic({0x1cc3740?, 0xc001a61d88?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/openperouter/openperouter/internal/conversion.APItoHostConfig(0xc000ee99e0?, {0xc001992c0f?, 0xc001c075f8?}, {0x8, {0xc0019ba2c0, 0x1, 0x1}, {0x31054a0, 0x0, 0x0}, ...})\n\t/go/openperouter/internal/conversion/host_conversion.go:31 +0x1505\ngithub.com/openperouter/openperouter/internal/controller/routerconfiguration.configureInterfaces({0x211e7b8, 0xc000e78420}, {{0xc0010b32c0, 0x24}, {{0x7f7c81344288, 0xc0006939a0}}, {0x8, {0xc0019ba2c0, 0x1, 0x1}, ...}})\n\t/go/openperouter/internal/controller/routerconfiguration/host_config.go:55 +0x448\ngithub.com/openperouter/openperouter/internal/controller/routerconfiguration.(*PERouterReconciler).Reconcile(0xc00017dea0, {0x211e7b8, 0xc000e78180}, {{{0xc0018e65e8?, 0x30?}, {0xc001889bf6?, 0xfffffffffffffffb?}}})\n\t/go/openperouter/internal/controller/routerconfiguration/underlay_vni_controller.go:153 +0x14b4\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000da3ad0?, {0x211e7b8?, 0xc000e78180?}, {{{0xc0018e65e8?, 0x0?}, {0xc001889bf6?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:119 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2138a20, {0x211e7f0, 0xc00027d130}, {{{0xc0018e65e8, 0x13}, {0xc001889bf6, 0x5}}}, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:340 +0x3ad\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2138a20, {0x211e7f0, 0xc00027d130})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300 +0x21b\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 127\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:198 +0x28f\n"}
```

**Steps to reproduce**
Install Multus and configure a NAD
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vethconf
  namespace: openperouter-system
  annotations:
    k8s.v1.cni.cncf.io/resourceName: vethconf
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "vethconf",
  "plugins": [
    {
       "type": "ptp",
       	"ipam": {
          "type": "host-local",
          "subnet": "10.250.1.0/24"
        }
    }
  ]
}'
```
Configure the `multusNetworkAnnotation` attribute (here using the Helm chart)
```yaml
openperouter:
  # -- Multus network annotation to be added to router pods
  multusNetworkAnnotation: "vethconf"
```
Create an `Underlay` without specifying a nic
```yaml
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: Underlay
metadata:
  name: underlay
  namespace: openperouter-system
spec:
  asn: 64530
  evpn:
    vtepcidr: 100.68.0.0/16
  neighbors:
    - asn: 64529
      address: 10.184.43.10
      ebgpMultiHop: true
```
Create a `L2VNI`
```yaml
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: L2VNI
metadata:
  name: l2red
  namespace: openperouter-system
spec:
  vni: 210
  vrf: red
  hostmaster:
    type: bridge
    autocreate: true
```

### PR DESCRIPTION
**Pull request by fdomain**
* specifying a NIC in the Underlay configuration was incorrectly mandatory, which prevented users from leveraging Multus to establish connectivity to the ToR.
* we now detect if the Router Pod has a `k8s.v1.cni.cncf.io/networks` annotation and propagate that information to subsequent calls.
* if no underlay NIC is specified and the multusEnabled flag is true, the logic for retrieving or moving the underlay interface into the router's netns is skipped, assuming that Multus has already handled the necessary setup.

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression
> /kind example

**What this PR does / why we need it**:
Fixes #150 

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix: allow omitting underlay NIC configuration when using Multus.
```

### CODE REVIEW

**Comment by fdomain** [comment]
@fedepaol the e2etests are passing locally on my laptop (46/46). Could it be some flakiness in the tests? Would be great if you could pull this PR on your side and test🙏

**Comment by fedepaol** [comment]
> @fedepaol the e2etests are passing locally on my laptop (46/46). Could it be some flakiness in the tests? Would be great if you could pull this PR on your side and test🙏

CI had some flakes _but not this much_. I'll test this on my side, in the meantime you can file a dummy PR to trigger CI and see where we are. Also, the status of the cluster (including CRs, pod logs and so on) after a test failure can be found in the gh action https://github.com/openperouter/openperouter/actions/runs/18949481172 , maybe it's worth a look.
Our e2es dump the state after each failure, so it should be easy (depending on the failure) to find the problem.

**Comment by fedepaol** [comment]
For the record, both this https://github.com/openperouter/openperouter/pull/161 and https://github.com/openperouter/openperouter/pull/160 are fully green (not touching anything)

**Comment by fdomain** [comment]
I found the issue and fixed it. The problem was that router pods were no longer restarting when underlay objects were deleted. This happened because I introduced a bug: the restart logic depends on an UnderlayRemovedError{} being thrown, but I mistakenly added a condition around the code handling that case. During e2e tests, the router pods were never restarted.
See: https://github.com/openperouter/openperouter/compare/a2e0e8c96015376b1f3079904715003d4cde0cd9..18f0ba17b18538831da5c087aa2fa9252725d5e5

So now the original behaviour is restored:
- if a Nic was specified in an Underlay object, and the Underlay is deleted => `hasAlreadyUnderlay` will be true and the error will be raised since `len(underlays) == 0`
- if there was no NIC specified, and the Underlay access was managed by a Multus annotation => `hasAlreadyUnderlay` will be false, and the pod won't be restarted since the configuration of that interface is not managed by the Underlay object.

File: internal/controller/routerconfiguration/underlay_vni_controller.go [hunk 1]
```diff
@@ -81,6 +81,10 @@ func (r *PERouterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
 		slog.Error("failed to fetch router pod", "node", r.MyNode, "error", err)
 		return ctrl.Result{}, err
 	}
+	multusEnabled := false
+	if _, ok := routerPod.Annotations["k8s.v1.cni.cncf.io/networks"]; ok {
```
Comment (fedepaol) [inline internal/controller/routerconfiguration/underlay_vni_controller.go]: what if we make this a parameter? We'll have to drive the annotation from the chart anyways.

File: internal/hostnetwork/underlay_test.go [hunk 2]
```diff
@@ -149,19 +149,32 @@ var _ = Describe("Underlay configuration should work when", func() {
...
+		Expect(err).NotTo(HaveOccurred())
+
+		Eventually(func(g Gomega) {
+			validateUnderlayInNS(g, testNs, true, params)
 		}, 30*time.Second, 1*time.Second).Should(Succeed())
 	})
 })
 
-func validateUnderlayInNS(g Gomega, ns netns.NsHandle, params UnderlayParams) {
+func validateUnderlayInNS(g Gomega, ns netns.NsHandle, skipMainNicCheck bool, params UnderlayParams) {
```
Comment (fedepaol) [inline internal/hostnetwork/underlay_test.go]: let's call this CheckUnderlayNic

File: internal/hostnetwork/underlay_test.go [hunk 3]
```diff
@@ -72,7 +72,7 @@ var _ = Describe("Underlay configuration should work when", func() {
 		Expect(err).NotTo(HaveOccurred())
 
 		Eventually(func(g Gomega) {
-			validateUnderlayInNS(g, testNs, params)
+			validateUnderlayInNS(g, testNs, false, params)
```
Comment (fedepaol) [inline internal/hostnetwork/underlay_test.go]: let's use a const instead of false. Something like "CheckUnderlay"

File: cmd/hostcontroller/main.go [hunk 4]
```diff
@@ -83,6 +84,7 @@ func main() {
 		"the location of the frr configuration file")
 	flag.IntVar(&args.reloadPort, "reloadport", 9080, "the port of the reloader process")
 	flag.StringVar(&args.criSocket, "crisocket", "/containerd.sock", "the location of the cri socket")
+	flag.BoolVar(&args.multusEnabled, "multus-enabled", false, "Whether Multus is enabled")
```
[the remark this answers is not in the document]
Comment (fedepaol) [reply cmd/hostcontroller/main.go]: same for all the variables / parameters along the same line
